name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.1]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - uses: goreleaser/goreleaser-action@v2
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v2
      with:
        name: json2hcl
        path: dist/*

    - uses: google-github-actions/release-please-action@v3
      with:
        release-type: go
        package-name: json2hcl
